version: "3"
services:
  redis:
    image: redis
    container_name: "redis"
    ports:
      - 6379:${REDIS_PORT}
    command: redis-server
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - 27017:${MONGODB_PORT}
    volumes:
        - ./mongodb:/data/db
  web:
    build: 
      context: .
    volumes:
      - .:/pybo
    env_file:
      - ./config.env
    ports:
      - "5000:5000"
    depends_on:
     - mongodb